### ISSUE TITLE
Install Clarifaction

### ISSUE THREAD

**Issue by wyhinton** [christophercrouzet/nvidia-warp-houdini#3]
Hello, 

Just wondering exactly what is meant by "Add the ./houdini folder to the HOUDINI_PATH environment variable.". 

Do you mean copy and paste the "nvidia-warp-houdini-main\houdini" in you're houdinig project's directory, or are we meant to alter our houdini.env file with the path of nvidia-warp-houdini-main\houdini on our system?

**Comment by christophercrouzet** [comment]
Hi @wyhinton!

There are a few ways to go about this but maybe the easiest would be to place that folder in one of the default paths defined in `HOUDINI_PATH`. To know which ones they are, you can try printing the following in a Python shell within Houdini: `import hou; print(hou.getenv("HOUDINI_PATH"))`.

The `houdini.env` file is indeed another way to go about it if you prefer keeping the warp's folder in another location.
