### ISSUE TITLE
RuntimeError: Error launching kernel 'run', argument 'pscale_array' expects an array with 1 dimension(s) but the passed array has 2 dimension(s).

### ISSUE THREAD

**Issue by lydd8888** [christophercrouzet/nvidia-warp-houdini#4]
Hi guys,

I installed the warp and tried to open the example bouncing ball file.

I installed the HDA directly in Houdini because if I put the folder into HOUDINI_PATH it will complain 

After I open the file I get error below in sop solver
`Python error: Traceback (most recent call last):
File "<stdin>", line 49, in <module>
File "C:\Users\rugliu\AppData\Local\Programs\Python\Python310\Lib\site-packages\warp\context.py", line 3155, in launch
pack_args(fwd_args, params)
File "C:\Users\rugliu\AppData\Local\Programs\Python\Python310\Lib\site-packages\warp\context.py", line 3132, in pack_args
params.append(pack_arg(kernel, arg_type, arg_name, a, device, adjoint))
File "C:\Users\rugliu\AppData\Local\Programs\Python\Python310\Lib\site-packages\warp\context.py", line 2912, in pack_arg
raise RuntimeError(
RuntimeError: Error launching kernel 'run', argument 'pscale_array' expects an array with 1 dimension(s) but the passed array has 2 dimension(s)`

Any idea how to solve it?

Thanks

**Comment by christophercrouzet** [comment]
Hi @lydd8888, thanks for reporting this issue and apologies for any inconvenience caused! I've just pushed new commits onto the `main` branch that should address this—if you get a chance, please let me know if that works for you!

**Comment by lydd8888** [comment]
Just test it. Works great! Thank you so much for fast update.

I just have 1 issue:
When I install the new HDA it is not available when I tab it. I installed the backup version 1 and replace it with the newer one, it will work.

I will do more test recently. 

Thanks!

**Comment by christophercrouzet** [comment]
Thanks for letting me know!

> When I install the new HDA it is not available when I tab it. I installed the backup version 1 and replace it with the newer one, it will work.
Did you restart Houdini? One way to know what HDAs are installed in Houdini is to open `Assets -> Assets Manager...` from the main menu. There you can search for `warp` and confirm whether it's listed under the section `Scanned Asset Library Directories`. If not, it hasn't been installed correctly (maybe its parent directory isn't listed in `HOUDINI_PATH`?).

![Screenshot from 2023-10-18 10-09-17](https://github.com/christophercrouzet/nvidia-warp-houdini/assets/1691255/b8a0b02b-18d2-45e0-b3ac-7f3a2294baab)


You could also manually install it with `Assets -> Install Asset Library...`, but you'd have to do that each time you restart Houdini so it's best to set-up the `HOUDINI_PATH` once and for all. I personally do it with a small wrapper like this one:

```
#!/usr/bin/env bash

export HOUDINI_PATH="${HOUDINI_PATH};/path/to/nvidia-warp-houdini/houdini;&"
export PYTHONPATH="${PYTHONPATH}:/path/to/warp"

houdini "$@"
```

**Comment by lydd8888** [comment]
Thanks for the tips! I manage to solve it by adding `HOUDINI_PATH = "D:\NvidiaWarp\HDA_Example\nvidia-warp-houdini\houdini;&"` in houdini.env file. I have never seen your way of adding an asset library. Is it just in Linux?

**Comment by christophercrouzet** [comment]
That's right, this snippet is for Linux. But something similar could be written for Windows and wrapped into a `.bat` file that you could use to start Houdini. However your solution of using a `houdini.env` file is probably even better! :+1:
